
DROP TABLE IF EXISTS quotes;
DROP TABLE IF EXISTS elvl;

CREATE TABLE quotes (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    isin CHAR(12) NOT NULL,
    bid FLOAT NOT NULL,
    ask FLOAT NOT NULL
);

CREATE TABLE elvl (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    isin CHAR(12) NOT NULL,
    price FLOAT
);


